export const BEACON_DISCOVERY_SUCCESS = "BEACON_DISCOVERY_SUCCESS";
export const BEACON_DISCOVERY_INIT = "BEACON_DISCOVERY_INIT";
export const BEACON_DISCOVERY_START = "BEACON_DISCOVERY_START";
export const BEACON_DISCOVERY_STOP = "BEACON_DISCOVERY_STOP";
export const BEACON_DISCOVERY_ERROR = "BEACON_DISCOVERY_ERROR";
