export const BEACON_DISCOVERY_SUCCESS = "BEACON_DISCOVERY_SUCCESS";
export const BEACON_DISCOVERY_INIT = "BEACON_DISCOVERY_INIT";
export const BEACON_DISCOVERY_START = "BEACON_DISCOVERY_START";
export const BEACON_DISCOVERY_STOP = "BEACON_DISCOVERY_STOP";
export const BEACON_DISCOVERY_ERROR = "BEACON_DISCOVERY_ERROR";

export const BEACON_RANGING_SUCCESS = "BEACON_RANGING_SUCCESS";
export const BEACON_RANGING_INIT = "BEACON_RANGING_INIT";
export const BEACON_RANGING_START = "BEACON_RANGING_START";
export const BEACON_RANGING_STOP = "BEACON_RANGING_STOP";
export const BEACON_RANGING_ERROR = "BEACON_RANGING_ERROR";
